### ISSUE TITLE
Store only working in valentine

### ISSUE THREAD

**Issue by yaboibutt3r** [VORPCORE/vorp_stores-lua#37]
I am able to buy items from the store in valentine but every other store ive tested has had this issue, 
> error during NUI callback menu_submit:  citizen:/scripting/lua/scheduler.lua:739:  SCRIPT ERROR:  @vorp_stores/client/client.lua:494:  bad argument #1 to 'for iterator' (table expected, got nil)
> OpenBuyMenu  (@vorp_stores/client/client.lua:494)
> ref  (@vorp_stores/client/client.lua:293)

**Comment by outsider31000** [comment]
because the store doesnt exist in your `Config.BuyItems`
if you have locations in the config that are not in the other files you will get error.

**Comment by yaboibutt3r** [comment]
well that's strange cause they are all stores that came preconfigured with the script, I haven't added any new stores.

**Comment by outsider31000** [comment]
the names of the stores must match exactly how it is in config maybe you changed the names?.

**Comment by yaboibutt3r** [comment]
ill look into that, thanks for the help

**Comment by yaboibutt3r** [comment]
havent seen any issue yet, but I am curios if the open menu vector3 cords are supposed to be different cause they are all the same instead of different locations that are supposed to correspond with the store? they all have the valentine cords

**Comment by outsider31000** [comment]
they dont have the same locations. each location has different coords.
![image](https://github.com/VORPCORE/vorp_stores-lua/assets/87246847/c2ff0090-a629-4d1e-be84-97c9bba49529)
this is where the prompt will be.

download a new copy cause what you have is not whats in here.
