### ISSUE TITLE
Linux fix

### ISSUE THREAD

**Issue by RizzooTv** [VORPCORE/vorp_stores-lua#5]
Will there ever be a fix for Linux to count the decimal point? Or did you just have bad luck as a Linux user?

would be a pity

**Comment by xrb936** [comment]
The easiest solution would be to eliminate decimal points.

**Comment by YourgenAP** [comment]
@AndrewR3K The problem of Linux is how it works with decimals. 1.50 in Windows will be 1.50 but in linux it can be 1.49999999999999999999

**Comment by YourgenAP** [comment]
@AndrewR3K If I understand right, it affects money

**Comment by outsider31000** [comment]
We support windows
